apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    storage.openshift.io/remove-from: mgmt
  name: azure-file-csi-driver-operator-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azure-file-csi-driver-operator-clusterrole
subjects:
- kind: ServiceAccount
  name: azure-file-csi-driver-operator
  namespace: openshift-cluster-csi-drivers
