apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: azure-disk-csi-driver-operator
  namespace: openshift-cloud-credential-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    capability.openshift.io/name: Storage+CloudCredential
spec:
  serviceAccountNames:
  - azure-disk-csi-driver-operator
  - azure-disk-csi-driver-controller-sa
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AzureProviderSpec
    permissions:
      - 'Microsoft.Compute/disks/*'
      - 'Microsoft.Compute/snapshots/*'
      - 'Microsoft.Compute/virtualMachineScaleSets/*/read'
      - 'Microsoft.Compute/virtualMachineScaleSets/read'
      - 'Microsoft.Compute/virtualMachineScaleSets/virtualMachines/write'
      - 'Microsoft.Compute/virtualMachines/*/read'
      - 'Microsoft.Compute/virtualMachines/write'
      - 'Microsoft.Resources/subscriptions/resourceGroups/read'
  secretRef:
    name: azure-disk-credentials
    namespace: openshift-cluster-csi-drivers
