apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus
  namespace: openshift-cluster-storage-operator
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    capability.openshift.io/name: Storage
  labels:
    role: alert-rules
spec:
  groups:
    - name: default-storage-classes.rules
      rules:
      - alert: MultipleDefaultStorageClasses
        expr:  max_over_time(default_storage_class_count[5m]) > 1
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "More than one default StorageClass detected."
          description: |
            Cluster storage operator monitors all storage classes configured in the cluster
            and checks there is not more than one default StorageClass configured.
          message: "StorageClass count check is failing (there should not be more than one default StorageClass)"
