kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: azure-file-csi-driver-operator-clusterrolebinding
  annotations:
    storage.openshift.io/remove-from: mgmt
subjects:
  - kind: ServiceAccount
    name: azure-file-csi-driver-operator
    namespace: openshift-cluster-csi-drivers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azure-file-csi-driver-operator-clusterrole
