apiVersion: operator.openshift.io/v1
kind: ClusterCSIDriver
metadata:
  name: file.csi.azure.com
  annotations:
    storage.openshift.io/remove-from: mgmt
spec:
  logLevel: Normal
  managementState: Managed
  operatorLogLevel: Normal
