- op: "add"
  path: "/rules/-"
  value:
    apiGroups:
      - ''
    resourceNames:
      - extension-apiserver-authentication
      - aws-ebs-csi-driver-operator-lock
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
