apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: powervs-block-csi-driver-operator-rolebinding
  namespace: ${CONTROLPLANE_NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: powervs-block-csi-driver-operator-role
subjects:
  - kind: ServiceAccount
    name: powervs-block-csi-driver-operator
    namespace: ${CONTROLPLANE_NAMESPACE}
